### ISSUE TITLE
JUnit 5 Support

### ISSUE THREAD

**Issue by toniedzwiedz** [Cognifide/knotx#417]
### Version used

* knot.x: 1.3.0+

### Context of the issue/feature

Starting with version 3.5.1, _Vert.x_ supports testing with JUnit 5 via [`vertx-junit5`](https://github.com/vert-x3/vertx-junit5/releases).

Using this utility would allow us to write cleaner and more expressive test code and give projects based on Knot.x more leeway in terms of what testing frameworks they use (the [JUnit 5 extension model](https://junit.org/junit5/docs/current/user-guide/#extensions) is more flexible than JUnit 4).

In order for that to happen:

1. Knot.x needs to be upgraded to use Vert.x 3.5.1. According to @Skejven, this is going to be surprisingly tricky due to an API incompatibility between Vert.x 3.5.0 and 3.5.1 that affects the way Knot.x handles POST requests. This will need to be part of a bigger milestone. See https://github.com/Cognifide/knotx/issues/346
2. A rewrite of the [Knot.x test utilities](https://github.com/Cognifide/knotx/tree/milestone/backpressure-and-configs/knotx-core/src/test/java/io/knotx/junit) to use `vertx-junit5`. JUnit 4 Rules need to be [converted to JUnit 5 extensions](http://www.codeaffine.com/2016/04/06/replace-rules-in-junit5/).
3. Tests can be rewritten. Surprisingly, this is optional as JUnit 5 allows a single project to execute tests using the new _JUnit Jupiter_ programming model side by side with legacy JUnit 4 tests via JUnit Vintage. This could be a gradual migration.

### Appendix:

This relies on the completion of https://github.com/Cognifide/knotx/issues/346

**Comment by marcinczeczko** [comment]
@toniedzwiedz - sounds perfect. Just FYI, together with the test refactor towards Junit5 we'd like to migrate to other test utilities, to make unit/it tests even more readable. These are:
- [assertj](http://joel-costigliola.github.io/assertj/) instead of hamcrest - to get fluent api instead of dozen of static imports that's hard to manage
- [rest assured](https://github.com/rest-assured/rest-assured) to simplify it tests that utilize HTTP calls, json, html validations

**Comment by toniedzwiedz** [comment]
@marcinczeczko JUnit 5 is completely agnostic in terms of what assertion library we use. It makes for a cool group of features to put in the same milestone but, as far as I understand, there's no dependency between the two.

Not sure about REST-assured. Do you know if it relies on JUnit 4 Runners or Rules?

**Comment by toniedzwiedz** [comment]
Vert.x 3.5.1 is now [available in Knot.x 1.3.0-SNAPSHOT](https://github.com/Knotx/knotx-dependencies/pull/1)

**Comment by tomaszmichalak** [comment]
Knot.x 1.3.0 is released. We use Vert.x 3.5.1 (`<vertx.stack.version>3.5.1</vertx.stack.version>`) so JUnit5 is ready to implement. It requires updates in:
- Knot.x rules (integration tests)
- integration tests
- unit tests

**Comment by tomaszmichalak** [comment]
Please start with an integration tests like: io.knotx.assembler.FragmentAssemblerTest

**Comment by tMaxx** [comment]
Current proposed roadmap is as follows (in order):

- [ ] Review and merge of Knotx/knotx-dependencies#2
- [ ] Review and merge of Knotx/knotx-junit5#1
- [ ] Review of Knotx/knotx-data-bridge#19
- [ ] Verify that knotx-data-bridge Travis CI build passed
- [ ] Merge Knotx/knotx-data-bridge#19

After all of that is finished, port knotx core's tests to v5 as well. Work on that is just starting, so this is more of a general topic than a task.

**Comment by tomaszmichalak** [comment]
Fixed.
